### PR TITLE
Fixing Google Colab link

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @markusschanta 

just fixing a link.

Cheers!

### CODE REVIEW

**Comment by markusschanta** [comment]
Hi @spekulatius , thank you very much for your help with keeping this list up to date! 👍

**Comment by spekulatius** [comment]
No worries, happy to help out @markusschanta

**Comment by markusschanta** [comment]
Super! If you find [awesome-jupyter](https://github.com/markusschanta/awesome-jupyter) useful and you could maybe link to it, mention it in your blog or [tweet about it](https://twitter.com/intent/retweet?tweet_id=1324628102476111873), that would be awesome. 😎

**Comment by spekulatius** [comment]
> Super! If you find [awesome-jupyter](https://github.com/markusschanta/awesome-jupyter) useful and you could maybe link to it, mention it in your blog or [tweet about it](https://twitter.com/intent/retweet?tweet_id=1324628102476111873), that would be awesome. sunglasses

Done :+1:

**Pull request merged**
