### PR TITLE
Add Naas ressources to list

### PR DESCRIPTION
**Pull request by BobCashStory**

### CODE REVIEW

**Review by markusschanta — CHANGES_REQUESTED** [review]
Hi @BobCashStory,

Thank you for your contribution. Happy to add naas to the list if you can please make the following changes:

- [x] Alphabetise the list where you add Naas as an entry.
- [x] Shorten/clarify the description: "JupyterLab environment with magic scheduling/notification functionaltiy and assets/dependency/secrets management".
- [x] Remove the link to the notebooks repo (there's not much there yet).

Cheers,
Markus

**Comment by markusschanta** [comment]
Hi @BobCashStory, do you still want Naas added to the [awesome-jupyter](https://github.com/markusschanta/awesome-jupyter)? I'm not allowed to make the aforementioned changes on your branch (otherwise I would have included them already).

**Comment by BobCashStory** [comment]
@markusschanta Done !

**Comment by markusschanta** [comment]
Great, I have merged this PR! 

Having said that, if you find [awesome-jupyter](https://github.com/markusschanta/awesome-jupyter) useful and you can help to spread the word by starring the repo/tweeting about it, that would be awesome. 😎

Cheers,
Markus

**Pull request merged**
