### PR TITLE
Add Kandi link

### PR DESCRIPTION
**Pull request by kandikits**
Hello - request review and approval on the inclusion of Explore Jupyter on your list.
It would be a good addition under COMMUNITY RESOURCES section of this article. Would you like to include it in your list? We'd love to hear your feedback.
Thanks!

### CODE REVIEW

**Comment by markusschanta** [comment]
Hi @kandikits,

Thank you for the suggestion. Looking at your link, it looks like there first 4 sections on the page are all empty.

I'd like to add this if there is more actual content available. Do you agree?

image

**Comment by kandikits** [comment]
Hi @markusschanta 

Thanks for your candid feedback and we totally agree that there needs to be some content in those 4 sections.

Check out this collection of Jupyter Libraries on kandi. It also has how-tos, Q&A, fixes, code snippets, ratings for each library. Check this & millions of open source libraries here: https://kandi.openweaver.com/explore/jupyter

Let us know your feedback on this page. Thanks!

**Review by kandikits — COMMENTED** [review]
Thanks for considering this link. And this looks awesome, will need your approval i believe to get published?

**Comment by markusschanta** [comment]
Hello,

Yes, I have shortened the description and fixed the Markdown link syntax so the tests pass as well. Going to merge this now.

In turn, if you find [awesome-jupyter](https://github.com/markusschanta/awesome-jupyter) useful and you could maybe link to it or [tweet about it](https://twitter.com/markusschanta/status/1324628102476111873), that would be awesome. 😎

Cheers,
Markus

**Comment by kandikits** [comment]
Hello @markusschanta - we have retweeted the tweet you shared, check if this is okay:
https://twitter.com/OpenWeaverInc/status/1564909596442890245?s=20&t=vsLMqPg6Pi4ZBFcnH3qh8A

**Pull request merged**
