### PR TITLE
Add PAWS in Hosted Notebook Solutions

### PR DESCRIPTION
**Pull request by ELC**
Add PAWS - https://wikitech.wikimedia.org/wiki/PAWS

### CODE REVIEW

**Comment by markusschanta** [comment]
Hi, Ezequiel! 👋

Thank you for your contribution! What do you think about the following description line for PAWS: "**Jupyter notebook deployment customized for interacting with Wikimedia wikis**"?

**Comment by ELC** [comment]
I was experimenting with it and I found no integration with wikimedia wikis. It is just a notebook server with token authentication. It is interesting as a JupyterHub alternative although one does not have persistence across sessions.

**Comment by markusschanta** [comment]
It seems to have []() and []() preinstalled. That allows you to query/modify Wikipedia pages programmatically out of the box, which lowers the barriers to do so. Qualifies as "customized for interacting with wikis" in my book...

I found that notebooks are still there when I log out/back in and stop/start the server. When you say "does not have persistence between sessions", what do you mean?

**Comment by ELC** [comment]
I didn't know about pywikibot a mwapi. In my case I created a test notebook and when I stop the server and then run it again, the notebook were gone.

**Comment by markusschanta** [comment]
Yeah, it looks pretty useful. I wanted to do some light Wikipedia scraping a while ago and this might actually be a nice platform to do it on.

Would you be fine with it if I change the description to "Jupyter notebook deployment customized for interacting with Wikimedia wikis"? This is mostly based on [how they are describing the project themselves](https://wikitech.wikimedia.org/wiki/PAWS) plus a bit of grammatical simplification.

**Comment by ELC** [comment]
Added as suggested!

**Comment by markusschanta** [comment]
Brilliant! Thank you for your contribution!

**Pull request merged**
