### PR TITLE
Add nbdev.fast.ai

### PR DESCRIPTION
**Pull request by leorochael**

### CODE REVIEW

**Comment by markusschanta** [comment]
Hi @leorochael! 👋

Thank you for your contribution. I've made some minor changes to your suggestion.

Cheers,
Markus

**Comment by markusschanta** [comment]
FYI @sgugger, @jph00, @hamelsmu, @pete88b: nbdev has been added to this list! 🎉

**Comment by jph00** [comment]
Thanks!

**Comment by leorochael** [comment]
Thanks for the acceptance @markusschanta.

Just a little nit-pick: If we're being strict about about alphabetizing the list, then `nbdev` should come between `nbconvert` and `nbinteract`... :wink:

**Comment by markusschanta** [comment]
Good spot, thanks! 

Fixed: https://github.com/markusschanta/awesome-jupyter/pull/77

A couple of other lists aren't in order either. At some point, I should have a go at it and put them in proper order as well. And maybe someday I'll get around to including proper integration checks...

**Pull request merged**
