### PR TITLE
Removing dead link (times out)

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @markusschanta 

the link times out for me (for a few times I've tried over the last days). I wouldn't include it as timeout isn't so awesome ;)

Cheers,
Peter

### CODE REVIEW

**Comment by markusschanta** [comment]
Awesome, even removed the roman "I" in the other link. 👌

**Comment by spekulatius** [comment]
> Awesome, even removed the roman "I" in the other link. ok_hand

Yup, I like stuff tidy :)

Man bleibt Deutscher, auch wenn man das Land verlaesst ;)

**Comment by markusschanta** [comment]
You can get take the Software Engineer out of Germany, but you can't take Germany out of the Software Engineer. 😁

**Comment by spekulatius** [comment]
> You can get take the Software Engineer out of Germany, but you can't take Germany out of the Software Engineer. grin

hahaha, exactly 😆️

**Pull request merged**
