### PR TITLE
Add awesome notebook list

### PR DESCRIPTION
**Pull request by BobCashStory**
An awesome list of public Jupyter Notebooks on all kinds of interesting topics, published by the Naas community.

This project is made for busy business & tech professionals that wants to take back control of data.

Check the list of notebooks :
The list is getting bigger everyday !

# CRM

- [Hubspot](https://github.com/jupyter-naas/awesome-notebooks/tree/master/CRM/Hubspot): Emails campaigns and contact management.

# Dataviz

- [Plotly](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Dataviz/Plotly) 
    - [Bubble chart](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Data%20Visualisation/Plotly)
    - [Candlestick](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Data%20Visualisation/Plotly)
    - [Gantt](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Data%20Visualisation/Plotly)
    - [Barchart](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Data%20Visualisation/Plotly)
    - [Linechart](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Data%20Visualisation/Plotly)
    - [Waterfall](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Data%20Visualisation/Plotly)
    - [Waterfall Advanced](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Data%20Visualisation/Plotly)

## Database

- [Airtable](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Database/Airtable)
- [MySQL](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Database/MySQL)
- [Snowflake](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Database/Snowflake)

## ERP

- [SAP](https://github.com/jupyter-naas/awesome-notebooks/tree/master/ERP/SAP-HANA)

## File parsing

- [ZIP](https://github.com/jupyter-naas/awesome-notebooks/tree/master/File%20parsing/ZIP)
- [CSV](https://github.com/jupyter-naas/awesome-notebooks/tree/master/File%20parsing/CSV)

## FTP

- [FTP](https://github.com/jupyter-naas/awesome-notebooks/tree/master/FTP/FTP)
- [FTPS](https://github.com/jupyter-naas/awesome-notebooks/tree/master/FTP/FTPS)

## Market Data

- [Quandl](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Maket%20Data/Quandl)
- [Yahoo-Finance](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Maket%20Data/Yahoo-Finance)

## Nass

- [Notebook as API](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Naas/Notebook_as_API)
- [Notebook Scheduler](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Naas/Scheduler)
- [Sharable Assets](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Naas/Shareable_assets)
- [Notifications](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Naas/Notifications)

## Project Management

- [Trello](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Project%20Management/Trello)

## Snippets

- [Delete not empty folder](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Snippets)
- [Embed webpage](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Snippets)

## Spreadsheets

- [Excel 365](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Spreadsheets/Excel%20365)
- [GSheets](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Spreadsheets/GSheets)

## Treasury

- [Neo](https://github.com/jupyter-naas/awesome-notebooks/tree/master/Treasury/Neo)

## World Data

- [COVID19 FR](https://github.com/jupyter-naas/awesome-notebooks/tree/master/World%20Open%20Data/COVID19) 
- [GDP per capital](https://github.com/jupyter-naas/awesome-notebooks/tree/master/World%20Open%20Data/Economic%20Data)
- [GDP per country](https://github.com/jupyter-naas/awesome-notebooks/tree/master/World%20Open%20Data/Economic%20Data)
- [Gini inex](https://github.com/jupyter-naas/awesome-notebooks/tree/master/World%20Open%20Data/Economic%20Data)
- [Most populated countries](https://github.com/jupyter-naas/awesome-notebooks/tree/master/World%20Open%20Data/Economic%20Data)
- [Top 10 richest region](https://github.com/jupyter-naas/awesome-notebooks/tree/master/World%20Open%20Data/Economic%20Data)
- [World GPD contributor](https://github.com/jupyter-naas/awesome-notebooks/tree/master/World%20Open%20Data/Economic%20Data)
- [World population and Density](https://github.com/jupyter-naas/awesome-notebooks/tree/master/World%20Open%20Data/Economic%20Data)

### CODE REVIEW

**Comment by BobCashStory** [comment]
@markusschanta can you have look on that one ?

**Comment by markusschanta** [comment]
Hi @BobCashStory,

I've added jupyter-naas/awesome-notebooks to the list in a separate [commit](https://github.com/markusschanta/awesome-jupyter/commit/b718fed69173fa863b082d66fa40a46c1b148c44). Since there's already a collection of notebooks in this list, I figured jupyter-naas/awesome-notebooks should be in the same section as that one. 

Somehow, I couldn't commit to your branch, so I made the changes separately.

Cheers,
Markus

**Comment by BobCashStory** [comment]
Ok thanks, i close this one

**Comment by markusschanta** [comment]
Cool, thanks!

**Pull request closed without merging**
