### PR TITLE
docs: fix simple typo, functionaltiy -> functionality

### PR DESCRIPTION
**Pull request by timgates42**
There is a small typo in README.md.

Should read `functionality` rather than `functionaltiy`.

Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

### CODE REVIEW

**Comment by markusschanta** [comment]
Hi @timgates42,

Many thanks for pointing out the typo! I'm almost surprised there aren't more. 😁

Was this the only tzpo your script flagged?

Cheers,
Markus

**Comment by timgates42** [comment]
Thanks @markusschanta - Yes but its not great at eliminating all the typos, there are generally a huge number of valid words that aren't dictionary words like stdlib functions e.g. strlen or company names like github or computer jargon like ipython so it goes for finding common misspellings that have a high chance of being a spelling errors rather than a comprehensive correction of all typos.

**Comment by markusschanta** [comment]
Yes, that seems reasonable. Sounds a bit like there are relatively more false positives than false negatives. Is that a fair categorisation?

**Comment by markusschanta** [comment]
Just out of curiosity: how do you select what repos to run `meticulous` against / how did you come across `awesome-jupyter`?

**Comment by timgates42** [comment]
I actually parse different awesome lists :) - I think awesome-jupyter  might have appeared on one of the awesome python lists

**Comment by timgates42** [comment]
Yes the false negatives are pretty rare, generally when people include a typo in the documentation to demonstrate handling of typos in search libraries, but I usual spot these from the context in the manual checking.

**Pull request merged**
